Feature/section footer
DamianJorga/portfolio pull request #7
Opened 2020-10-05 09:55 UTC by DamianJorga

2020-10-05 13:27 UTC, greg-top requested changes
kilka zmian w kodzie wymaganych. Co do designu to wszystko OK

2020-10-05 13:27 UTC, greg-top commented on images/icons/right-arrow (1).svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
nazwa pliku do zmiany, usun niepotrzebny numer na koncu nazwy

2020-10-05 13:27 UTC, greg-top commented on index.html
> +    <footer class="footer" id="contact">
hmmmm,

twoj footer sklada sie z 2 sekcji:
1.) contact
2.) bottom footer

moze przenisiesz to id do kontenera ponizej (class="container"). Wiem, ze w przypadku tej kotwicy, ktora uzywasz w menu niewiele sie zmieni, ale bd to wygladalo profesjonalnie

2020-10-05 13:27 UTC, greg-top commented on index.html
> +                <label class="contact-label" for="FormControlInput">your name:</label>
zle stworzona labelka, atrybut for musi wskazywac input, np.
`<label class="contact-label" for="name">your name:</label>
                <input type="text" id="name "class="form-item form-control">`

2020-10-05 13:27 UTC, greg-top commented on index.html
> +                <input type="text" class="form-item form-control">
brak id dla pola formularza, zerknij na podany snippet w poprzednim komentarzu jaka wystepuje relacja miedzy znacnikiem label i input.

Popraw dla reszty pol formularza

2020-10-05 13:27 UTC, greg-top commented on index.html
> +                <label class="contact-label" for="FormControlInput">company:</label>
zmien pole formularza company na phone number i nadaj inputowi type="tel"

2020-10-05 13:27 UTC, greg-top commented on index.html
> +              <button type="button" class="footer--btn btn text-center mx-auto">Napisz do mnie <span><img class="btn--arrow" src="images/icons/right-arrow (1).svg" alt=""></span></button>
dobrze uzyty element <span>! :)

2020-10-05 13:27 UTC, greg-top commented on index.html
> +          <div class="col-12 col-sm-6 col-md-4 text-white text-center">
tutaj przydalaby sie jakas nowa sekcja, albo kontener z odpowiednia klasa -> class="footer__address"

2020-10-05 13:27 UTC, greg-top commented on src/sass/layout/components/_footer.scss
> +    background-color: #181818;
moze zmienna?

2020-10-05 13:27 UTC, greg-top commented on src/sass/layout/pages/_scroll-to-top.scss
> +    background-image: icons-url('top.png'); // zmienic kolor ikony (nie widac za ciemna)
dobry komentarz :), zmien to od razu przy poprawianiu PR

2020-10-05 22:56 UTC, DamianJorga commented on src/sass/layout/components/_footer.scss
> +    background-color: #181818;
zmienna jest utworzona w innym branchu zmienie jak polacze

2020-10-06 08:27 UTC, greg-top approved these changes

2020-10-06 08:33 UTC, merged